name: CI
on:
  pull_request:
jobs:
  job1:
    runs-on: ubuntu-latest
    name: build
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          java-version: '23'
          distribution: 'adopt'
      - name: Grant execution permissions to Gradle wrapper
        working-directory: RentelService
        run: chmod +x ./gradlew
      - name: Build and test
        working-directory: RentelService
        run: |
          export SHELL=/bin/bash
          ./gradlew build
